=== mohamedelghaouth/projXML/shm.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
   
   <xsd:element name="nom" type="xsd:string"/>
   <xsd:element name="DateDuJour" type="xsd:date"/>
   <xsd:element name="h" type="xsd:time" />
   <xsd:element name="num" type="xsd:string"/>
   <xsd:element name="cap" type="xsd:string"/>
   
   <xsd:element name="hoccp" >
   <xsd:complexType>
            <xsd:sequence>
				<xsd:element ref="h"  minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
    </xsd:complexType>
    </xsd:element>
   
    <xsd:element name="sale">
        <xsd:complexType>
             <xsd:sequence>
				<xsd:element ref="num"/>
                <xsd:element ref="hoccp"  minOccurs="0" maxOccurs="unbounded"/>
				 <xsd:element ref="cap"/>
             </xsd:sequence>
    </xsd:complexType>
	 </xsd:element>
	 
	 <xsd:element name="etage">
        <xsd:complexType>
            <xsd:sequence>
				<xsd:element ref="num" />
                <xsd:element ref="sale"  minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
    </xsd:complexType>
	</xsd:element>
	
	<xsd:element name="block">
        <xsd:complexType>
            <xsd:sequence>
				<xsd:element ref="nom"/>
                <xsd:element ref="etage"  minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
    </xsd:complexType>
	</xsd:element>

	<xsd:element name="ecole">
        <xsd:complexType>
            <xsd:sequence>
				<xsd:element ref="nom"/>
				<xsd:element ref="DateDuJour"  minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="block" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
	
	
</xsd:schema>

=== mohamedelghaouth/projXML/p1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsldemo.xsl"?>
<ecole xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shm.xsd">
  <nom>Ensah</nom>
  <DateDuJour>2019-01-15</DateDuJour>
  <block>
    <nom>b1</nom>
    <etage>
      <num>1</num>
      <sale>
        <num>1</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>25</cap>
      </sale>
      <sale>
        <num>2</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>25</cap>
      </sale>
    </etage>
    <etage>
      <num>2</num>
      <sale>
        <num>3</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>10</cap>
      </sale>
      <sale>
        <num>4</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>15</cap>
      </sale>
    </etage>
  </block>
  <block>
    <nom>2</nom>
    <etage>
      <num>1</num>
      <sale>
        <num>5</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>15</cap>
      </sale>
      <sale>
        <num>6</num>
        <hoccp>
          <h>10:30:00</h>
          <h>12:30:00</h>
        </hoccp>
        <cap>14</cap>
      </sale>
    </etage>
  </block>
</ecole>
